import { MonsterCard } from '../schemas/card.js';

export const MONSTER_CARDS: MonsterCard[] = [
  {
    id: 'kuriboh',
    name: 'Kuriboh',
    cardType: 'monster',
    monsterType: 'fiend',
    attribute: 'dark',
    level: 1,
    attack: 300,
    defense: 200,
    description: 'A small, furry creature that is harmless but can multiply.',
    effect: 'During damage calculation, if this card battles: You can send this card from your hand to the Graveyard; you take no battle damage from that battle.',
    isEffectMonster: true,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'common'
  },
  {
    id: 'elemental_hero_sparkman',
    name: 'Elemental HERO Sparkman',
    cardType: 'monster',
    monsterType: 'warrior',
    attribute: 'light',
    level: 4,
    attack: 1600,
    defense: 1400,
    description: 'An Elemental HERO with the power of lightning.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'common'
  },
  {
    id: 'blue_eyes_white_dragon',
    name: 'Blue-Eyes White Dragon',
    cardType: 'monster',
    monsterType: 'dragon',
    attribute: 'light',
    level: 8,
    attack: 3000,
    defense: 2500,
    description: 'This legendary dragon is a powerful engine of destruction.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'ultra_rare'
  },
  {
    id: 'dark_magician',
    name: 'Dark Magician',
    cardType: 'monster',
    monsterType: 'spellcaster',
    attribute: 'dark',
    level: 7,
    attack: 2500,
    defense: 2100,
    description: 'The ultimate wizard in terms of attack and defense.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'ultra_rare'
  },
  {
    id: 'red_eyes_black_dragon',
    name: 'Red-Eyes Black Dragon',
    cardType: 'monster',
    monsterType: 'dragon',
    attribute: 'dark',
    level: 7,
    attack: 2400,
    defense: 2000,
    description: 'A ferocious dragon with a deadly attack.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'ultra_rare'
  },
  {
    id: 'summoned_skull',
    name: 'Summoned Skull',
    cardType: 'monster',
    monsterType: 'fiend',
    attribute: 'dark',
    level: 6,
    attack: 2500,
    defense: 1200,
    description: 'A fiend with dark powers for confusing the enemy.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'rare'
  },
  {
    id: 'celtic_guardian',
    name: 'Celtic Guardian',
    cardType: 'monster',
    monsterType: 'warrior',
    attribute: 'earth',
    level: 4,
    attack: 1400,
    defense: 1200,
    description: 'An elf who learned to wield a sword, he baffles enemies with swift attacks.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'common'
  },
  {
    id: 'feral_imp',
    name: 'Feral Imp',
    cardType: 'monster',
    monsterType: 'fiend',
    attribute: 'dark',
    level: 4,
    attack: 1300,
    defense: 1400,
    description: 'A small fiend that feeds on decaying corpses.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'common'
  },
  {
    id: 'gaia_the_fierce_knight',
    name: 'Gaia the Fierce Knight',
    cardType: 'monster',
    monsterType: 'warrior',
    attribute: 'earth',
    level: 7,
    attack: 2300,
    defense: 2100,
    description: 'A knight whose horse travels faster than the wind.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'rare'
  },
  {
    id: 'curse_of_dragon',
    name: 'Curse of Dragon',
    cardType: 'monster',
    monsterType: 'dragon',
    attribute: 'dark',
    level: 5,
    attack: 2000,
    defense: 1500,
    description: 'A wicked dragon that taps into dark forces to execute a powerful attack.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'common'
  },
  {
    id: 'mystical_elf',
    name: 'Mystical Elf',
    cardType: 'monster',
    monsterType: 'spellcaster',
    attribute: 'light',
    level: 4,
    attack: 800,
    defense: 2000,
    description: 'A delicate elf that lacks offense, but has a terrific defense backed by mystical power.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'common'
  },
  {
    id: 'winged_dragon_guardian_of_fortress',
    name: 'Winged Dragon, Guardian of the Fortress #1',
    cardType: 'monster',
    monsterType: 'dragon',
    attribute: 'wind',
    level: 4,
    attack: 1400,
    defense: 1200,
    description: 'A dragon commonly found guarding mountain fortresses.',
    isEffectMonster: false,
    isTuner: false,
    isSpirit: false,
    isUnion: false,
    isGemini: false,
    isFlip: false,
    rarity: 'common'
  }
];
